"""Local Streamlit interface for the ProteoTrace synthetic demonstration."""

from __future__ import annotations

from pathlib import Path
from tempfile import TemporaryDirectory

import pandas as pd
import streamlit as st

from src.qc import batch_response_table, missingness_by_sample, outlier_samples, validate_inputs
from src.statistics import differential_by_response


st.set_page_config(page_title="ProteoTrace", page_icon="🧬", layout="wide")
st.title("ProteoTrace")
st.caption("Auditable proteomics QC and biomarker analysis. Research use only, not clinical decision support.")

st.warning("Use synthetic or appropriately approved, de-identified data only. Review every result with a qualified researcher.")

with st.sidebar:
    st.header("Inputs")
    protein_file = st.file_uploader("Protein-abundance CSV", type="csv")
    metadata_file = st.file_uploader("Clinical-metadata CSV", type="csv")
    use_demo = st.checkbox("Use included synthetic demonstration data", value=True)

if use_demo:
    proteins = pd.read_csv("data/synthetic_protein_matrix.csv")
    metadata = pd.read_csv("data/synthetic_clinical_metadata.csv")
elif protein_file and metadata_file:
    proteins = pd.read_csv(protein_file)
    metadata = pd.read_csv(metadata_file)
else:
    st.info("Upload both files or select the included synthetic demonstration data.")
    st.stop()

findings = validate_inputs(proteins, metadata)
if findings:
    st.error("Input validation failed")
    for finding in findings:
        st.write(f"- {finding}")
    st.stop()

st.success(f"Validated {len(proteins)} samples and {len(proteins.columns) - 1} proteins.")

tab_qc, tab_results, tab_governance = st.tabs(["Quality control", "Biomarker comparison", "Governance"])
with tab_qc:
    left, right = st.columns(2)
    with left:
        st.subheader("Sample missingness")
        st.dataframe(missingness_by_sample(proteins), width="stretch")
    with right:
        st.subheader("Outlier screen")
        st.dataframe(outlier_samples(proteins), width="stretch")
    st.subheader("Batch by response")
    st.dataframe(batch_response_table(metadata), width="stretch")

with tab_results:
    st.subheader("Responder versus non-responder comparison")
    results = differential_by_response(proteins, metadata)
    st.dataframe(results, width="stretch")
    st.caption("Uses Welch t-tests for the synthetic two-group demonstration. Real-study modelling must account for design, covariates, multiplicity, and repeated measures.")
    st.bar_chart(results.set_index("protein")["mean_difference"])

with tab_governance:
    st.subheader("Human review is mandatory")
    st.markdown("""
    - This demonstration does not diagnose disease or recommend treatment.
    - Statistical outputs are generated by deterministic code, not a language model.
    - A future AI report assistant may explain tool outputs but must cite files and sources.
    - Do not use identifiable, unpublished, or unapproved clinical data.
    """)
